-- Increase ID column length from 36 to 100 characters
-- This allows for longer prefixed IDs like "artist_USERID" format

SET FOREIGN_KEY_CHECKS=0;

-- USERS TABLE
ALTER TABLE users MODIFY COLUMN id VARCHAR(100) NOT NULL;

-- ARTISTS TABLE
ALTER TABLE artists MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE artists MODIFY COLUMN user_id VARCHAR(100) NOT NULL;

-- SONGS TABLE
ALTER TABLE songs MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE songs MODIFY COLUMN user_id VARCHAR(100) NOT NULL;
ALTER TABLE songs MODIFY COLUMN artist_id VARCHAR(100) NOT NULL;
ALTER TABLE songs MODIFY COLUMN flagged_by VARCHAR(100);
ALTER TABLE songs MODIFY COLUMN approved_by VARCHAR(100);

-- TRACKS TABLE
ALTER TABLE tracks MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE tracks MODIFY COLUMN song_id VARCHAR(100) NOT NULL;

-- SESSIONS TABLE
ALTER TABLE sessions MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE sessions MODIFY COLUMN user_id VARCHAR(100) NOT NULL;

-- ACCOUNTS TABLE
ALTER TABLE accounts MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE accounts MODIFY COLUMN user_id VARCHAR(100) NOT NULL;
ALTER TABLE accounts MODIFY COLUMN provider_account_id VARCHAR(100);

-- VERIFICATION TABLE
ALTER TABLE verification MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE verification MODIFY COLUMN identifier VARCHAR(100);
ALTER TABLE verification MODIFY COLUMN user_id VARCHAR(100);

-- UPLOADS TABLE
ALTER TABLE uploads MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE uploads MODIFY COLUMN user_id VARCHAR(100) NOT NULL;

-- ADMIN TABLES
ALTER TABLE admin MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE admin MODIFY COLUMN user_id VARCHAR(100) NOT NULL;
ALTER TABLE admin MODIFY COLUMN approved_by VARCHAR(100);

ALTER TABLE admin_task MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE admin_task MODIFY COLUMN created_by VARCHAR(100) NOT NULL;
ALTER TABLE admin_task MODIFY COLUMN assigned_to VARCHAR(100);

-- EMAIL LOG TABLE
ALTER TABLE email_log MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE email_log MODIFY COLUMN user_id VARCHAR(100);

-- NOTIFICATION TABLE
ALTER TABLE notification MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE notification MODIFY COLUMN user_id VARCHAR(100) NOT NULL;

-- ROYALTY TABLE
ALTER TABLE royalty MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE royalty MODIFY COLUMN user_id VARCHAR(100) NOT NULL;
ALTER TABLE royalty MODIFY COLUMN song_id VARCHAR(100);

SET FOREIGN_KEY_CHECKS=1;

-- Verify changes
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN ('id', 'user_id', 'artist_id', 'song_id')
  AND TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME, COLUMN_NAME;
